apiVersion: ingestion.sneaksanddata.com/v1alpha1
kind: DataRoute
metadata:
  name: consumer1
spec:
  consumerId: consumer1
  schemaSubject: consumer1-raw
  schemaVersion: 1
---
apiVersion: ingestion.sneaksanddata.com/v1alpha1
kind: DataRoute
metadata:
  name: consumer2
spec:
  consumerId: consumer2
  schemaSubject: consumer2-event
  schemaVersion: 1
  payloadSchema: |
    {
      "type": "record",
      "name": "Consumer2Event",
      "namespace": "com.sneaksanddata.ingestion",
      "fields": [
        { "name": "id",      "type": "string" },
        { "name": "payload", "type": { "type": "map", "values": "string" } }
      ]
    }
