apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# todo: rewrite the config handler, so it accepts envvars
data:
  application.toml: |
    [server]
    host = {{ .Values.settings.server.host | quote }}
    port = {{ .Values.settings.server.port }}
    nThreads = {{ .Values.settings.server.nThreads }}
    maxContentLengthBytes = {{ .Values.settings.server.maxContentLengthBytes }}

    [router]
    api_version = {{ .Values.settings.router.apiVersion | quote }}

    [dynamodb]
    region = {{ .Values.settings.dynamodb.region | quote }}
    tableName = {{ .Values.settings.dynamodb.tableName | quote }}
    {{- if .Values.settings.dynamodb.endpoint }}
    endpoint = {{ .Values.settings.dynamodb.endpoint | quote }}
    {{- end }}
    autoCreateTable = {{ .Values.settings.dynamodb.autoCreateTable }}
