name: Build Container Image
run-name: Build arcane-push-stream Image for GHCR from ${{ github.ref }} by @${{ github.actor }}

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_image:
    name: Build Docker Image and Helm Charts
    runs-on: ubuntu-latest
    env:
      TOKEN: '${{ secrets.MAVEN_PUBLISH_TOKEN }}'
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        id: image_name
        run: echo "value=${IMAGE_NAME,,}" >> "$GITHUB_OUTPUT"
        env:
          IMAGE_NAME: ${{ github.repository }}

      - name: Get project version
        uses: SneaksAndData/github-actions/generate_version@6c8187f0d8c167a9410a76bed2e98409449ed495 # v0.1.11
        id: version

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{steps.version.outputs.version}}
          flavor:
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          use: true
          platforms: linux/arm64,linux/amd64

      - name: Create and use a new builder instance
        run: |
          docker buildx create --name mybuilder --use

      - name: Build and push Docker image
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          cache-from: type=registry,ref=ghcr.io/${{ steps.image_name.outputs.value }}:cache
          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=ghcr.io/${{ steps.image_name.outputs.value }}:cache
          context: .
          file: .container/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          secrets: |
            github_token=${{ secrets.MAVEN_PUBLISH_TOKEN }}

      - name: Build and Push Chart
        uses: SneaksAndData/github-actions/build_helm_chart@6c8187f0d8c167a9410a76bed2e98409449ed495 # v0.1.11
        with:
          application: arcane-stream-json
          app_version: ${{ steps.meta.outputs.version }}
          container_registry_user: ${{ github.actor }}
          container_registry_token: ${{ secrets.GITHUB_TOKEN }}
          container_registry_address: ghcr.io/sneaksanddata/
